Repository MutinyWallet/mutiny-node, pull requests merged in 2023-11, with the labels that each got.

#819 Initial onion message routing
  mutiny-core/src/node.rs
  mutiny-core/src/peermanager.rs
Labels: ldk

#833 Fix contacts sync with empty names
  Cargo.lock
  mutiny-core/Cargo.toml
  mutiny-core/src/labels.rs
  mutiny-core/src/lib.rs
  mutiny-core/src/nostr/mod.rs
  mutiny-core/src/nostr/nwc.rs
  mutiny-wasm/Cargo.toml
Labels: bug

#856 LDK in std mode
  Cargo.lock
  Cargo.toml
  mutiny-core/Cargo.toml
  mutiny-core/src/lib.rs
  mutiny-wasm/Cargo.toml
Labels: ldk

#859 Make activity sort more stable
  mutiny-core/src/nodemanager.rs
Labels: bug

#864 Unfilter force cloes balance
  docs/Testing.md
  mutiny-core/src/nodemanager.rs
Labels: bug

#865 Return proper NWC errors on skipped invoices
  mutiny-core/src/nostr/nwc.rs
Labels: nostr

#873 Mock pay invoice for Node
  mutiny-core/src/node.rs
  mutiny-core/src/nostr/mod.rs
  mutiny-core/src/nostr/nwc.rs
  mutiny-core/src/test_utils.rs
Labels: tests

#876 Add specific error for HTLC limits
  mutiny-core/src/node.rs
  mutiny-core/src/nodemanager.rs
Labels: LDK
