Repository MutinyWallet/mutiny-node, pull requests merged in 2024-02, with the labels that each got.

#1006 Fix labeling
  mutiny-core/src/lib.rs
  mutiny-core/src/node.rs
  mutiny-core/src/nodemanager.rs
  mutiny-wasm/src/lib.rs
Labels: bug

#1008 Fix the fedimint sweep fee for max balance
  mutiny-core/src/federation.rs
  mutiny-core/src/lib.rs
Labels: fedimint

#1009 Swap label on fedimint sweep payment
  mutiny-core/src/lib.rs
Labels: bug, fedimint

#1010 Make node manager locks RwLocks
  mutiny-core/src/lib.rs
  mutiny-core/src/nodemanager.rs
Labels: LDK

#1023 Set swap label before paying invoice
  mutiny-core/src/lib.rs
Labels: bug, fedimint

#1017 Start up optimizations grab bag
  mutiny-core/src/auth.rs
  mutiny-core/src/federation.rs
  mutiny-core/src/gossip.rs
  mutiny-core/src/lib.rs
  mutiny-core/src/node.rs
  mutiny-core/src/nodemanager.rs
  mutiny-core/src/test_utils.rs
  mutiny-core/src/utils.rs
  mutiny-wasm/src/indexed_db.rs
  mutiny-wasm/src/lib.rs
Labels: LDK, fedimint

#1002 Update ldk 121, bdk alpha5, bitcoin 0.30
  Cargo.lock
  Cargo.toml
  mutiny-core/Cargo.toml
  mutiny-core/src/error.rs
  mutiny-core/src/event.rs
  mutiny-core/src/federation.rs
  mutiny-core/src/fees.rs
  mutiny-core/src/gossip.rs
  mutiny-core/src/key.rs
  mutiny-core/src/keymanager.rs
  mutiny-core/src/labels.rs
  mutiny-core/src/ldkstorage.rs
  mutiny-core/src/lib.rs
  mutiny-core/src/lnurlauth.rs
  mutiny-core/src/logging.rs
  mutiny-core/src/lsp/lsps.rs
  mutiny-core/src/node.rs
  mutiny-core/src/nodemanager.rs
  mutiny-core/src/nostr/mod.rs
  mutiny-core/src/nostr/nwc.rs
  mutiny-core/src/onchain.rs
  mutiny-core/src/peermanager.rs
  mutiny-core/src/scorer.rs
  mutiny-core/src/storage.rs
  mutiny-core/src/test_utils.rs
  mutiny-core/src/utils.rs
  mutiny-core/src/vss.rs
  mutiny-wasm/Cargo.toml
  mutiny-wasm/src/error.rs
  mutiny-wasm/src/indexed_db.rs
  mutiny-wasm/src/lib.rs
  mutiny-wasm/src/models.rs
Labels: BDK, LDK

#992 Create nostr profile
  Cargo.lock
  mutiny-core/Cargo.toml
  mutiny-core/src/labels.rs
  mutiny-core/src/lib.rs
  mutiny-core/src/nostr/mod.rs
  mutiny-core/src/nostr/nwc.rs
  mutiny-core/src/storage.rs
  mutiny-wasm/Cargo.toml
  mutiny-wasm/src/error.rs
  mutiny-wasm/src/lib.rs
  mutiny-wasm/src/models.rs
Labels: nostr

#1036 Update to rust-nostr 0.28.0
  Cargo.lock
  mutiny-core/Cargo.toml
  mutiny-core/src/error.rs
  mutiny-core/src/labels.rs
  mutiny-core/src/lib.rs
  mutiny-core/src/nostr/mod.rs
  mutiny-core/src/nostr/nip49.rs
  mutiny-core/src/nostr/nwc.rs
  mutiny-core/src/test_utils.rs
  mutiny-core/src/utils.rs
  mutiny-wasm/Cargo.toml
  mutiny-wasm/src/lib.rs
Labels: nostr

#1039 Generate node's uuid deterministically
  mutiny-core/src/keymanager.rs
  mutiny-core/src/node.rs
  mutiny-core/src/nodemanager.rs
Labels: LDK

#1041 Allow dm decrypting to fail
  mutiny-core/src/lib.rs
Labels: nostr

#1044 Update fedimint
  Cargo.lock
  mutiny-core/Cargo.toml
  mutiny-wasm/Cargo.toml
Labels: bug, fedimint

#1051 Don't save federation to storage until after init
  mutiny-core/src/federation.rs
  mutiny-core/src/lib.rs
Labels: bug, fedimint

#1049 Only check voltage invoice is within 10 sats
  mutiny-core/src/lsp/voltage.rs
  mutiny-core/src/node.rs
  mutiny-core/src/test_utils.rs
Labels: bug

#1053 Add federation code to list_federations
  mutiny-core/src/federation.rs
  mutiny-core/src/lib.rs
Labels: fedimint

#1050 `lightning-liquidity` alpha release
  Cargo.lock
  mutiny-core/Cargo.toml
  mutiny-core/src/lsp/lsps.rs
  mutiny-core/src/lsp/mod.rs
  mutiny-core/src/lsp/voltage.rs
  mutiny-core/src/node.rs
Labels: LDK
