Repository MutinyWallet/mutiny-node, pull requests merged in 2024-01, with the labels that each got.

#937 Call process events after a disconnect
  mutiny-core/src/networking/socket.rs
Labels: LDK

#938 Don't save already paid invoices to pending list
  mutiny-core/src/nostr/nwc.rs
Labels: nostr

#953 Move channel config load after watch_channel
  mutiny-core/src/ldkstorage.rs
  mutiny-core/src/lsp/mod.rs
  mutiny-core/src/node.rs
Labels: bug, LDK

#954 Nostr contacts fixes
  Cargo.lock
  Cargo.toml
  mutiny-core/src/labels.rs
  mutiny-core/src/lib.rs
  mutiny-core/src/storage.rs
  mutiny-wasm/src/indexed_db.rs
Labels: nostr

#957 Verify fedimint network
  mutiny-core/src/federation.rs
Labels: fedimint

#958 Sync non-nostr contacts
  mutiny-core/src/lib.rs
  mutiny-core/src/utils.rs
Labels: nostr

#964 RBF fee bumping utilities
  mutiny-core/src/error.rs
  mutiny-core/src/nodemanager.rs
  mutiny-core/src/onchain.rs
  mutiny-wasm/src/lib.rs
Labels: BDK

#965 Set invoice labels after fedimint payment
  mutiny-core/src/lib.rs
  mutiny-core/src/node.rs
  mutiny-core/src/nodemanager.rs
  mutiny-wasm/src/lib.rs
Labels: bug, fedimint

#956 Add utilities for nip05
  Cargo.lock
  mutiny-core/Cargo.toml
  mutiny-core/src/error.rs
  mutiny-core/src/utils.rs
  mutiny-wasm/src/lib.rs
Labels: nostr

#971 Update rust-nostr
  Cargo.lock
  Cargo.toml
  mutiny-core/Cargo.toml
  mutiny-core/src/error.rs
  mutiny-core/src/lib.rs
  mutiny-core/src/nostr/mod.rs
  mutiny-core/src/nostr/nwc.rs
  mutiny-core/src/test_utils.rs
  mutiny-core/src/utils.rs
  mutiny-wasm/Cargo.toml
Labels: nostr

#959 update to latest liquidity lib
  Cargo.lock
  mutiny-core/Cargo.toml
  mutiny-core/src/lsp/lsps.rs
  mutiny-core/src/node.rs
Labels: LDK

#967 DM requests for invoices
  Cargo.lock
  mutiny-core/Cargo.toml
  mutiny-core/src/error.rs
  mutiny-core/src/lib.rs
  mutiny-core/src/nostr/mod.rs
  mutiny-core/src/nostr/nwc.rs
  mutiny-core/src/storage.rs
  mutiny-wasm/Cargo.toml
  mutiny-wasm/src/error.rs
  mutiny-wasm/src/lib.rs
  mutiny-wasm/src/models.rs
Labels: nostr

#981 Timestamp NWC filters
  mutiny-core/src/lib.rs
  mutiny-core/src/nostr/mod.rs
  mutiny-core/src/nostr/nwc.rs
  mutiny-core/src/storage.rs
  mutiny-core/src/utils.rs
Labels: nostr

#996 Set invoice labels before sending
  mutiny-core/src/lib.rs
Labels: bug
