Repository MutinyWallet/mutiny-node, pull requests merged in 2024-05, with the labels that each got.

#1168 More federation metadata parsing
  mutiny-core/src/federation.rs
  mutiny-core/src/lib.rs
Labels: fedimint

#1166 Enable anchor channels and scid aliases
  mutiny-core/Cargo.toml
  mutiny-core/src/lib.rs
  mutiny-core/src/node.rs
  mutiny-core/src/nodemanager.rs
Labels: LDK

#1158 Hermes Tests
  mutiny-core/src/blindauth.rs
  mutiny-core/src/federation.rs
  mutiny-core/src/hermes.rs
Labels: tests

#1164 Return better NWC error code for payment failures
  mutiny-core/src/nostr/nwc.rs
Labels: nostr

#1146 Add on chain for federations
  mutiny-core/src/federation.rs
  mutiny-core/src/lib.rs
  mutiny-core/src/nodemanager.rs
  mutiny-core/src/onchain.rs
  mutiny-core/src/storage.rs
  mutiny-wasm/src/lib.rs
  mutiny-wasm/src/models.rs
Labels: fedimint

#1172 Fix duplicate payment when paying lightning address
  mutiny-core/src/federation.rs
  mutiny-core/src/lib.rs
Labels: bug

#1190 Fetch federation info from invite code if not on nostr
  mutiny-core/src/federation.rs
  mutiny-core/src/nostr/mod.rs
Labels: fedimint

#1191 Add NIP98 auth for nostr.build
  mutiny-core/src/lib.rs
Labels: nostr

#1187 Match NWC events by p tag instead event pk
  mutiny-core/src/nostr/mod.rs
Labels: nostr
